spring.application.name=pigmyMobileApp
server.port=${PORT:8080}
camel.servlet.mapping.context-path=/*
rest.api.base.url=/pigmyMobile/v2
agent.resource.path=${rest.api.base.url}/agent
transaction.resource.path=${rest.api.base.url}/transaction
user.resource.path=${rest.api.base.url}/user
agent.login.path=${rest.api.base.url}/login

# ===============================
# Database Connection
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/pigmy
#spring.datasource.username=root
#spring.datasource.password=pavan123

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/pigmy
spring.datasource.username=2a9eev67hBUc7LY.root
spring.datasource.password=nPn3k2LMVjBSEgc2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
